services:
  qwen-asr-api:
    image: arianpg/qwen-asr-api:cuda
    environment:
      - DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
